version: "3.9"
networks:
  default:
    name: zef-network
services:
  zef:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=zef_postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=zef
  zef_postgresql:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./zef/volumes/postgres-data
