version: "3.9"
networks:
  default:
    name: zef-network
services:
  zef_postgresql:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./dumps/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - ./postgres-data:/var/lib/postgresql/data
  zef:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=zef_postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=zef
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  postgres-data:
