version: "3.9"
networks:
  default:
    name: zef-network
services:
  zef_postgresql:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./dumps/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - ./postgres-data:/var/lib/postgresql/data
  zef:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - APP_PORT=3000
      - DB_HOST=zef_postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=zef
      - JWT_SECRET_KEY=secret
      - JWT_EXPIRES_IN=24h
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SQS_URL=
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 5
  zef_terraform:
    image: hashicorp/terraform:1.2.9
    volumes:
      - ./infrastructure/main.tf:/infrastructure/main.tf
      - ./terraform-data:/infrastructure
    working_dir: /infrastructure
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=

volumes:
  postgres-data:
